'use strict';

exports.seed = function(knex, Promise) {
  return knex('books').insert([
  {
    title: "Secondhand",
    photographer : "Misc.",
    nationality : "Misc.",
    type : "Exhibition Catalog",
    genre : "",
    textby : "",
    publisher : "Pier 24 Photography",
    isbn : "978-0-9839917-5-5",
    year : "2014",
    tags : "archives, appropriation, institutions, Bay Area, curation",
    comments : "What an interesting show.",
    signed : false,
    created_at: new Date(),
    updated_at: new Date(),
    user_id: 7
  },
{
  title: "Protest Photographs",
  photographer : "Chauncey Hare",
  nationality : "American",
  type : "Monograph",
  genre : "Documentary",
  textby : "Chauncey Hare, Judy Wyatt, Jack von Euw",
  publisher : "SteidlKasher",
  isbn : "978-3-86521-495-9",
  year : "2009",
  tags : "B&W, domesticity, interiors, home, family, political, California, labor, Suburbs",
  comments : "",
  signed : false,
  created_at: new Date(),
  updated_at: new Date(),
  user_id: 7
},
{
  title : "Incidents",
  photographer : "Henry Wessel",
  nationality : "American",
  type : "Monograph",
  genre : "Street",
  textby : "",
  publisher : "Steidl",
  isbn : "978-3-86930-697-1",
  year : "2013",
  tags : "B&W, California, Bay Area, American West",
  comments : "Has a sense of humor",
  signed : true,
  created_at: new Date(),
  updated_at: new Date(),
  user_id: 7
},
{
  title: "The Photographer's Eye",
  photographer : "Misc.",
  nationality : "American",
  type : "Exhibition Catalog",
  genre : "Curation",
  textby : "John Szarkowski",
  publisher : "The Museum of Modern Art",
  isbn : "978-0-87070-527-4",
  year : "2007",
  tags : "institutions, curation, theory",
  comments : "A canonical work.",
  signed : false,
  created_at: new Date(),
  updated_at: new Date(),
  user_id: 7
},
{
  title: "Dive Dark Dream Slow",
  photographer : "Melissa Catanese",
  nationality : "American",
  type : "Monograph",
  genre : "Curation",
  textby : "",
  publisher : "MACK",
  isbn : "978-0-9823653-7-3",
  year : "2012",
  tags : "archives, appropriation, curation, collection, vernacular, metaphysical",
  comments : "Pictures from the collection of Peter J. Cohen",
  signed : true,
  created_at: new Date(),
  updated_at: new Date(),
  user_id: 7
},
{
  title: "Songbook",
  photographer : "Alec Soth",
  nationality : "American",
  type : "Monograph",
  genre : "Documentary",
  textby : "",
  publisher : "The Ice Plant",
  isbn : "9781910164020",
  year : "2015",
  tags : "B&W, Landscape, Portraiture, North America, United States, community, metaphysical, surreal",
  comments : "",
  signed : true,
  created_at: new Date(),
  updated_at: new Date(),
  user_id: 7
},
{
  title: "Hotel Oracle",
  photographer : "Jason Fulford",
  nationality : "American",
  type : "Monograph",
  genre : "",
  textby : "",
  publisher : "The Soon Institute",
  isbn : "978-90-810584-4-5",
  year : "2013",
  tags : "color, squares, formal, travel, literary, metaphysical",
  comments : "",
  signed : false,
  created_at: new Date(),
  updated_at: new Date(),
  user_id: 7
},
{
  title: "Disco Night Sept 11",
  photographer : "Peter Van Agtmael",
  nationality : "American",
  type : "Monograph",
  genre : "Photojournalism",
  textby : "Peter Van Agtmael",
  publisher : "Red Hook Editions",
  isbn : "978-0-9841954-2-8",
  year : "2014",
  tags : "Arab World, the middle east, conflict, war, trauma, photojournalism, reportage, violence, politics, military, Iraq, Afghanistan",
  comments : "",
  signed : false,
  created_at: new Date(),
  updated_at: new Date(),
  user_id: 7
},
])
}
